apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: negocio-microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: negocio-microservice
        tier: backend
    spec:
      containers:
      - name: negocio-microservice
        image: jovaniac/negocio-microservice:0.0.1-SNAPSHOT
        ports:
      - containerPort: 8086 