#https://stackoverflow.com/questions/35845144/how-can-i-create-a-mysql-db-with-docker-compose
version: '3'
services:
  postgres_ofertas:
    build: postgres #con build se puede asociar un dockerfile
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5434:5432"
    volumes:
      - ./blockstorage_dev/postgres:/var/lib/postgresql/data
  ofertas:
    image: jovaniac/ofertas-microservice:0.0.1-snapshot
    links:
      - postgres_ofertas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_ofertas:5432/hazloakki_ofertas
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
    depends_on:
      - postgres_ofertas
    ports:
      - '8089:8089'