#https://stackoverflow.com/questions/35845144/how-can-i-create-a-mysql-db-with-docker-compose
version: '3'
services:
  postgres:
    build: postgres #con build se puede asociar un dockerfile
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5433:5432"
    volumes:
      - ./blockstorage_dev/postgres:/var/lib/postgresql/data
  