apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account
        tier: backend
    spec:
      containers:
      - name: account
        image: jovaniac/cuenta-microservice:0.0.1-SNAPSHOT
        ports:
      - containerPort: 8085 