kind: Service
apiVersion: v1
metadata:
  name: servicio-ofertas
  selector:
    # Esta etiqueta la usa k8s para buscar el pod
    # al que le enviara el trafico. Un error aqui 
    # hara que no funcione el ruteo.
    app: servicio-ofertas
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089

    

